package metrorail;
import java.awt.Color;
import java.util.Calendar;
import java.util.Random;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JFrame;


public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        j1 = new javax.swing.JRadioButton();
        j2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jc1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        j5 = new javax.swing.JRadioButton();
        j6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jc2 = new javax.swing.JComboBox<>();
        jcombo2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        j9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        j7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        j12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        j11 = new javax.swing.JLabel();
        j13 = new javax.swing.JLabel();
        j14 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        j15 = new javax.swing.JLabel();
        j16 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setViewportView(jEditorPane1);

        jScrollPane2.setViewportView(jEditorPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 61)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText(" Metro Rail Ticketing System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metrorail/m2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(1150, 778));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("       Route: Uttara to Motijheel       ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("                              Only for Uttara area");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        j1.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j1.setText("A/C");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j2.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j2.setText("Non A/C");
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 0, 22)); // NOI18N
        jLabel3.setText("Condition");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jc1.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        jc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pallabi", "Mirpur-11", "Mirpur-10", "Kazipara", "Shewrapara", "Agargaon", "Bijoy Sarani", "Farmgate", "Karwan Bazar", "Shahbag", "Dhaka University", "Secretariat", "Motijheel" }));
        jc1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Britannic Bold", 0, 22)); // NOI18N
        jLabel7.setText("Destination");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel8.setFont(new java.awt.Font("Britannic Bold", 0, 22)); // NOI18N
        jLabel8.setText("Person");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        j5.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j5.setText("Adult");
        j5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });

        j6.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j6.setText("Child ");
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jButton1.setText("OK");
        jButton1.setActionCommand("");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.setActionCommand("");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jButton5.setText("RESET");
        jButton5.setActionCommand("");
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jc2.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        jc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        jc2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc2ActionPerformed(evt);
            }
        });

        jcombo2.setFont(new java.awt.Font("Britannic Bold", 0, 22)); // NOI18N
        jcombo2.setText("Number of Tickets");
        jcombo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("(Less than 10 years old)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(j6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j6)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcombo2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel9.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel9.setText("Passenger's Copy");

        jLabel10.setFont(new java.awt.Font("Britannic Bold", 0, 22)); // NOI18N
        jLabel10.setText("Condition");

        j9.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel13.setFont(new java.awt.Font("Britannic Bold", 0, 22)); // NOI18N
        jLabel13.setText("Person");

        j7.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel18.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        jLabel18.setText("From");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel22.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        jLabel22.setText("To");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel23.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        jLabel23.setText("Date");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        j12.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel25.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        jLabel25.setText("Time");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        j11.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        j13.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        j14.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel29.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        jLabel29.setText("Ticket No.");

        jLabel19.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        jLabel19.setText("Price");

        j15.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        j16.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel30.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        jLabel30.setText("BDT");

        j3.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        j4.setFont(new java.awt.Font("Britannic Bold", 0, 20)); // NOI18N
        j4.setText(" Tickets");
        j4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton2.setFont(new java.awt.Font("Britannic Bold", 0, 22)); // NOI18N
        jButton2.setText("Get your ticket");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j4, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(j3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(j7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(j13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        
if(j1.isSelected()&&j2.isSelected())
{
    
    JOptionPane.showMessageDialog(null,"Please select only one box!");
    
    
}
else if(j5.isSelected()&&j6.isSelected())
{
    JOptionPane.showMessageDialog(null,"Please select only one box!");
}
else if(j1.isSelected()&&j2.isSelected()&&j5.isSelected()&&j6.isSelected())
{
    JOptionPane.showMessageDialog(null,"Please select only one box!");
}

else if((j1.isSelected()||j2.isSelected())&&(j5.isSelected()||j6.isSelected())||(j2.isSelected()&&j5.isSelected()))
{
    Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat(" HH:mm:ss");
        j14.setText(tTime.format(timer.getTime()));
        
        SimpleDateFormat tDate = new SimpleDateFormat(" dd-MMM-yyyy");
        j13.setText(tDate.format(timer.getTime()));
        
        j11.setText(" Uttara");
        j12.setText(" "+(String) jc1.getSelectedItem());
        
        int cg= (int)(Math.random()*(9230-1220)+1+1220);
        j15.setText(" "+Integer.toString(cg)+"MTS");
    if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Motijheel"))
        {
           
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 60");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Pallabi"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 20");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Mirpur-11"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 24");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Mirpur-10"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 24");
            
        }
          else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Kazipara"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 30");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Shewrapara"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 30");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Agargaon"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 36");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Bijoy Sarani"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 40");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Farmgate"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 44");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Karwan Bazar"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 44");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Shahbag"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 50");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Dhaka University"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 50");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Secretariat"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 56");
            
        }
       
        else if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Motijheel"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 30");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Pallabi"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 10");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Mirpur-11"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 12");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Mirpur-10"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 12");
            
        }
          else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Kazipara"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 15");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Shewrapara"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 15");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Agargaon"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 18");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Bijoy Sarani"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 20");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Farmgate"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 22");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Karwan Bazar"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 22");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Shahbag"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 25");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Dhaka University"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 25");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Secretariat"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 28");
            
        }
         else if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Motijheel"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 50");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Pallabi"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 10");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Mirpur-11"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 14");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Mirpur-10"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 14");
            
        }
          else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Kazipara"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 20");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Shewrapara"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 20");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Agargaon"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 26");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Bijoy Sarani"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 30");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Farmgate"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 34");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Karwan Bazar"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 34");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Shahbag"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 40");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Dhaka University"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 40");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Secretariat"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 46");
            
        }
        
         else if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Motijheel"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 20");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Pallabi"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Adult");
            j16.setText(" 8");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Mirpur-11"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 8");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Mirpur-10"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 8");
            
        }
          else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Kazipara"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 8");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Shewrapara"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 8");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Agargaon"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 8");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Bijoy Sarani"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 10");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Farmgate"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 12");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Karwan Bazar"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 12");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Shahbag"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 15");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Dhaka University"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 15");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("1") && jc1.getSelectedItem().equals("Secretariat"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 1");
            j4.setText(" Ticket");
            j9.setText(" Child");
            j16.setText(" 18");
            
        }
         else if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Motijheel"))
        {
           
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 120");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Pallabi"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 40");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Mirpur-11"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Ticket2");
            j9.setText(" Adult");
            j16.setText(" 48");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Mirpur-10"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 48");
            
        }
          else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Kazipara"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 60");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Shewrapara"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 60");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Agargaon"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 72");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Bijoy Sarani"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 80");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Farmgate"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 88");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Karwan Bazar"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 88");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Shahbag"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 100");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Dhaka University"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 100");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Secretariat"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 112");
            
        }
    
         else if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Motijheel"))
        {
           
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 60");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Pallabi"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 20");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Mirpur-11"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 24");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Mirpur-10"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 24");
            
        }
          else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Kazipara"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 30");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Shewrapara"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 30");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Agargaon"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 36");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Bijoy Sarani"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 40");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Farmgate"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 44");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Karwan Bazar"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 44");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Shahbag"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 50");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Dhaka University"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 50");
            
        }
         else  if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Secretariat"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 56");
            
        }
    else if((j1.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Motijheel"))
        {
           
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 120");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Pallabi"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 32");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Mirpur-11"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 40");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Mirpur-10"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 40");
            
        }
          else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Kazipara"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 40");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Shewrapara"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 40");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Agargaon"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 52");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Bijoy Sarani"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 60");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Farmgate"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 68");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Karwan Bazar"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 68");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Shahbag"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 80");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Dhaka University"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 80");
            
        }
         else  if((j1.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Secretariat"))
        {
            
            j7.setText(" A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 92");
            
        }
    
    else if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Motijheel"))
        {
           
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 40");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Pallabi"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 18");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Mirpur-11"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 20");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Mirpur-10"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 20");
            
        }
          else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Kazipara"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 20");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Shewrapara"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 20");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Agargaon"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 22");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Bijoy Sarani"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 24");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Farmgate"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 24");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Karwan Bazar"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 24");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Shahbag"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 30");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Dhaka University"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 30");
            
        }
         else  if((j2.isSelected()) && j6.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Secretariat"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Child");
            j16.setText(" 36");
            
        }
     else if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Motijheel"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 60");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Pallabi"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 20");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Mirpur-11"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 24");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Mirpur-10"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 24");
            
        }
          else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Kazipara"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 30");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Shewrapara"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 30");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Agargaon"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 36");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Bijoy Sarani"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 40");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Farmgate"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 44");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Karwan Bazar"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 44");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Shahbag"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 50");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Dhaka University"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 50");
            
        }
         else  if((j2.isSelected()) && j5.isSelected() && jc2.getSelectedItem().equals("2") && jc1.getSelectedItem().equals("Secretariat"))
        {
            
            j7.setText(" Non A/C");
            j3.setText(" 2");
            j4.setText(" Tickets");
            j9.setText(" Adult");
            j16.setText(" 56");
            
        }
       
    
    
         
}

   else
{
    JOptionPane.showMessageDialog(null,"Please select one box in each section!");
}
         
        
         
         
         
       
         
         
         
         

        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       
       
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.yellow);
    }//GEN-LAST:event_formWindowActivated

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        j1.setSelected(false);
        j2.setSelected(false);
        j3.setText("");
        j4.setText("");
        j5.setSelected(false);
        j6.setSelected(false);
        j7.setText("");
        
        j9.setText("");
        j11.setText("");
        j12.setText("");
        j13.setText("");
        j14.setText("");
        j15.setText("");
        j16.setText("");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton1MouseClicked

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here
        
        
    }//GEN-LAST:event_j1ActionPerformed

    private void jc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc2ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       if (j11.getText().equals(""))
           
       {
             JOptionPane.showMessageDialog(null,"Please fill up each box in every section!");
       
       }
       else if(j1.isSelected()&&j2.isSelected())
           {
                 JOptionPane.showMessageDialog(null,"Please select only one box!");
           }
        else if(j5.isSelected()&&j6.isSelected())
           {
                 JOptionPane.showMessageDialog(null,"Please select only one box!");
           }
        else if(j1.isSelected()&&j2.isSelected()&&j5.isSelected()&&j6.isSelected())
           {
                 JOptionPane.showMessageDialog(null,"Please select only one box!");
           }
       
        else
        { 
              Ticket2 ob2 = new Ticket2();
              ob2.setVisible(true);
             //ob2.setBounds(100,100 , 433, 508);
              ob2.setResizable(false);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton j1;
    private javax.swing.JLabel j11;
    private javax.swing.JLabel j12;
    private javax.swing.JLabel j13;
    private javax.swing.JLabel j14;
    private javax.swing.JLabel j15;
    private javax.swing.JLabel j16;
    private javax.swing.JRadioButton j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JRadioButton j5;
    private javax.swing.JRadioButton j6;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jc1;
    private javax.swing.JComboBox<String> jc2;
    private javax.swing.JLabel jcombo2;
    // End of variables declaration//GEN-END:variables
}
